import type { ThreadComment } from "@/registry/ui/comment-thread"
import type { SupportConversation, SupportFolder, SupportInboxCopy } from "@/registry/blocks/support-inbox"
import type { TicketDeskCopy, TicketRecord } from "@/registry/blocks/ticket-desk"
import type { DeskNotification, NotificationInboxCopy } from "@/registry/blocks/notification-inbox"
import type { DeskOption } from "@/registry/lib/inbox"

export const brumaAgent = "Mateo Rulfo"

export const brumaChannels: DeskOption[] = [
  { value: "mail", label: "Correo" },
  { value: "phone", label: "Teléfono" },
  { value: "counter", label: "Mostrador" },
]

export const brumaAssignees: DeskOption[] = [
  { value: "Mateo Rulfo", label: "Mateo Rulfo" },
  { value: "Clara Neri", label: "Clara Neri" },
  { value: "Bruno Hale", label: "Bruno Hale" },
  { value: "Nuria Paz", label: "Nuria Paz" },
]

export const brumaTeams: DeskOption[] = [
  { value: "obra", label: "Obra" },
  { value: "cuentas", label: "Cuentas" },
  { value: "horno", label: "Horno" },
]

export const brumaPriorities: DeskOption[] = [
  { value: "none", label: "Sin prioridad" },
  { value: "low", label: "Baja" },
  { value: "medium", label: "Media" },
  { value: "high", label: "Alta" },
  { value: "urgent", label: "Urgente" },
]

export const brumaStatuses: DeskOption[] = [
  { value: "open", label: "Abierta" },
  { value: "progress", label: "En curso" },
  { value: "hold", label: "En espera" },
  { value: "resolved", label: "Resuelta" },
  { value: "closed", label: "Cerrada" },
]

export const brumaTypes: DeskOption[] = [
  { value: "task", label: "Tarea" },
  { value: "problem", label: "Problema" },
  { value: "incident", label: "Incidencia" },
]

export const brumaFolders: SupportFolder[] = [
  { id: "inbox", label: "Tu bandeja", section: "folders", icon: "inbox" },
  { id: "mentions", label: "Menciones", section: "folders", icon: "at-sign" },
  { id: "created", label: "Creadas por ti", section: "folders", icon: "pencil" },
  { id: "all", label: "Todas", section: "folders", icon: "layers" },
  { id: "unassigned", label: "Sin asignar", section: "folders", icon: "user" },
  { id: "spam", label: "No deseado", section: "folders", icon: "ban" },
  { id: "starred", label: "Destacadas", section: "views", icon: "star" },
  { id: "priority", label: "Prioridad alta", section: "views", icon: "flag" },
  { id: "snoozed", label: "Pospuestas", section: "views", icon: "clock" },
  { id: "obra", label: "Obra", section: "teams", icon: "users" },
  { id: "cuentas", label: "Cuentas", section: "teams", icon: "users" },
  { id: "horno", label: "Horno", section: "teams", icon: "users" },
]

export const brumaSuggestions = [
  "Te aparto la placa y sale el jueves.",
  "¿Te sirve pasar por el taller a las once?",
  "Ya revisé el horno: se quedó en 980.",
]

export const brumaSnippets = [
  { id: "hello", label: "Saludo", body: "Hola, soy Mateo del taller Bruma. " },
  { id: "delay", label: "Demora", body: "La pieza se queda un día más en el horno. " },
  { id: "close", label: "Cierre", body: "Quedo atento al tono con la luz del norte." },
]

export const brumaEmojis = ["🙂", "👍", "🔥", "✨"]

export const brumaSupportCopy: Partial<SupportInboxCopy> = {
  title: "Bandeja",
  compose: "Nueva conversación",
  search: "Buscar conversaciones",
  folders: "Carpetas",
  views: "Vistas",
  teams: "Bandejas del equipo",
  emptyFolder: "Esta carpeta está vacía",
  emptyFolderHint: "Cuando llegue algo, aparece aquí.",
  emptySelection: "Elige una conversación",
  emptySelectionHint: "El hilo se abre en este panel.",
  open: (count) => (count === 1 ? "1 abierta" : `${count} abiertas`),
  sortActivity: "Última actividad",
  sortUnread: "No leídas primero",
  collapse: "Ocultar carpetas",
  expand: "Mostrar carpetas",
  star: "Destacar",
  unstar: "Quitar destacado",
  snooze: "Posponer",
  unsnooze: "Reanudar",
  more: "Más acciones",
  unassign: "Quitar asignación",
  spam: "Marcar como no deseado",
  details: "Detalles",
  hideDetails: "Ocultar detalles",
  close: "Cerrar",
  back: "Volver",
  reply: "Responder",
  note: "Nota",
  send: "Enviar",
  sendHint: "⌘↵",
  seen: "Visto",
  unseen: "Sin ver",
  now: "Ahora",
  newTitle: "Nueva conversación",
  newDescription: "Escribe a alguien de fuera del taller.",
  name: "Nombre",
  company: "Casa",
  channel: "Canal",
  email: "Correo",
  subject: "Asunto",
  message: "Mensaje",
  save: "Crear",
  cancel: "Cancelar",
  viewContact: "Ver contacto",
  online: "En línea",
  offline: "Desconectado",
  away: "Ausente",
  assignee: "Responsable",
  team: "Bandeja del equipo",
  priority: "Prioridad",
  status: "Estado",
  lead: "Datos del contacto",
  attributes: "Datos de la conversación",
  tags: "Etiquetas",
  none: "Ninguno",
  folderLabel: "Carpeta",
}

export const brumaConversations: SupportConversation[] = [
  {
    id: "c-ines",
    name: "Inés Soler",
    email: "ines@faro-litoral.example",
    company: "Faro Litoral",
    location: "Puerto Escondido",
    presence: "online",
    subject: "Muestra del esmalte Niebla",
    preview: "Si el gris se ve frío con la luz del norte, avísame.",
    time: "16:40",
    unread: 2,
    assignee: "Mateo Rulfo",
    team: "obra",
    priority: "medium",
    status: "open",
    channel: "mail",
    mentions: true,
    tags: ["niebla", "faro"],
    attributes: [
      { label: "Canal", value: "Correo" },
      { label: "Casa", value: "Faro Litoral" },
      { label: "Lugar", value: "Puerto Escondido" },
    ],
    messages: [
      { id: "m1", author: "Inés Soler", body: "La barra de la cocina pide el mismo gris que la jarra del comedor. ¿Alcanza con una placa?", time: "15:10", side: "incoming" },
      { id: "m2", author: "Mateo Rulfo", body: "Te aparto una placa de Niebla y sale con el chofer del jueves.", time: "15:22", side: "outgoing", receipt: "seen" },
      { id: "m3", author: "Clara Neri", body: "La primera placa se rompió en el taller. Esta segunda no se cobra.", time: "15:41", side: "outgoing", note: true },
      { id: "m4", author: "Inés Soler", body: "Gracias. Si el gris se ve frío con la luz del norte, avísame.", time: "16:40", side: "incoming" },
    ],
  },
  {
    id: "c-nuria",
    name: "Nuria Paz",
    email: "nuria@bruma.example",
    company: "Estudio Bruma",
    presence: "away",
    subject: "Junta del muro de loseta",
    preview: "El jueves a las once cabe en la obra.",
    time: "ayer",
    assignee: "Nuria Paz",
    team: "obra",
    priority: "low",
    status: "progress",
    channel: "phone",
    attributes: [{ label: "Canal", value: "Teléfono" }],
    messages: [
      { id: "m1", author: "Nuria Paz", body: "El muro de la cocina ya tiene la nivelación. ¿Llevas el plano de juntas?", time: "ayer", side: "incoming" },
      { id: "m2", author: "Mateo Rulfo", body: "Lo llevo. El jueves a las once estoy en la obra.", time: "ayer", side: "outgoing", receipt: "unseen" },
    ],
  },
  {
    id: "c-clara",
    name: "Clara Neri",
    email: "clara@bruma.example",
    company: "Estudio Bruma",
    presence: "offline",
    subject: "Cobro repetido de la loseta",
    preview: "El pedido 184 salió dos veces en la cuenta del Faro.",
    time: "lun",
    unread: 1,
    assignee: "Clara Neri",
    team: "cuentas",
    priority: "high",
    status: "open",
    channel: "mail",
    starred: true,
    attributes: [{ label: "Pedido", value: "184" }],
    messages: [
      { id: "m1", author: "Clara Neri", body: "El pedido 184 de loseta se cobró dos veces. El segundo cargo hay que devolverlo al Faro.", time: "lun", side: "incoming" },
    ],
  },
  {
    id: "c-bruno",
    name: "Bruno Hale",
    email: "bruno@bruma.example",
    company: "Estudio Bruma",
    presence: "online",
    subject: "El horno 2 se quedó corto",
    preview: "Llegó a 980 y no pasó de ahí.",
    time: "lun",
    assignee: "Bruno Hale",
    team: "horno",
    priority: "urgent",
    status: "open",
    channel: "counter",
    messages: [
      { id: "m1", author: "Bruno Hale", body: "El horno 2 llegó a 980 y se quedó. La carga de Niebla no vitrificó.", time: "lun", side: "incoming" },
    ],
  },
  {
    id: "c-spam",
    name: "Taller Ajeno",
    email: "promo@ajeno.example",
    subject: "Horno nuevo sin costo",
    preview: "Responde este correo y te regalamos un horno.",
    time: "dom",
    spam: true,
    status: "closed",
    messages: [
      { id: "m1", author: "Taller Ajeno", body: "Responde este correo y te regalamos un horno.", time: "dom", side: "incoming" },
    ],
  },
  {
    id: "c-sal",
    name: "Nuria Paz",
    email: "nuria@bruma.example",
    subject: "Recordar el esmalte Sal",
    preview: "Lo pidió para la terraza de mayo.",
    time: "vie",
    snoozed: true,
    assignee: "Mateo Rulfo",
    team: "obra",
    priority: "low",
    status: "hold",
    messages: [
      { id: "m1", author: "Nuria Paz", body: "Deja apuntado el esmalte Sal para la terraza de mayo.", time: "vie", side: "incoming" },
    ],
  },
]

export const brumaTicketCopy: Partial<TicketDeskCopy> = {
  title: "Piezas",
  create: "Nueva pieza",
  search: "Buscar piezas",
  count: (count) => (count === 1 ? "1 pieza" : `${count} piezas`),
  empty: "No hay piezas",
  emptyHint: "Prueba otro estado.",
  emptySelection: "Elige una pieza",
  properties: "Propiedades",
  hideProperties: "Ocultar propiedades",
  edit: "Editar",
  remove: "Borrar",
  confirmTitle: "¿Borrar esta pieza?",
  confirmBody: "Sale del escritorio del taller.",
  confirm: "Borrar",
  cancel: "Cancelar",
  reply: "Responder",
  note: "Nota",
  send: "Enviar",
  sendHint: "⌘↵",
  seen: "Visto",
  unseen: "Sin ver",
  now: "Ahora",
  back: "Volver",
  newTitle: "Nueva pieza",
  editTitle: "Editar pieza",
  formDescription: "Asunto, quien la pide y la fecha prometida.",
  subject: "Asunto",
  description: "Descripción",
  requester: "Solicitante",
  email: "Correo",
  type: "Tipo",
  priority: "Prioridad",
  channel: "Canal",
  assignee: "Responsable",
  due: "Fecha prometida",
  status: "Estado",
  save: "Guardar",
  filter: "Estado",
  addFilter: "Añadir filtro",
  overdue: "Vencida",
  sla: "Plazo",
  tags: "Etiquetas",
  created: "Creada",
  updated: "Actualizada",
}

export const brumaTickets: TicketRecord[] = [
  {
    id: "t-horno",
    code: "BRU-18",
    subject: "El horno 2 no sostiene la temperatura",
    description: "La carga se queda en 980 y el esmalte no cierra.",
    requester: "Bruno Hale",
    email: "bruno@bruma.example",
    status: "open",
    priority: "high",
    type: "problem",
    channel: "counter",
    assignee: "Bruno Hale",
    due: "2026-10-01",
    created: "28 sep 2026",
    updated: "5 oct 2026",
    opened: "Abierta en el mostrador · 28 sep 2026",
    sla: { text: "Vencido desde el jueves", overdue: true },
    tags: ["horno", "niebla"],
    messages: [
      { id: "m1", author: "Bruno Hale", body: "Ayer la curva se detuvo en 980. La Niebla salió cruda.", time: "28 sep, 18:12", side: "incoming" },
      { id: "m2", author: "Mateo Rulfo", body: "Mañana reviso el termopar antes de la siguiente carga.", time: "29 sep, 09:04", side: "outgoing", receipt: "seen" },
    ],
  },
  {
    id: "t-placa",
    code: "BRU-22",
    subject: "Placa de Niebla para la barra del Faro",
    description: "Inés quiere ver el gris con la luz del norte antes de encargar el muro.",
    requester: "Inés Soler",
    email: "ines@faro-litoral.example",
    status: "progress",
    priority: "medium",
    type: "task",
    channel: "mail",
    assignee: "Mateo Rulfo",
    due: "2026-10-20",
    created: "2 oct 2026",
    updated: "4 oct 2026",
    opened: "Abierta por correo · 2 oct 2026",
    sla: { text: "Dentro de plazo", overdue: false },
    tags: ["faro"],
    messages: [
      { id: "m1", author: "Inés Soler", body: "¿Puedes traer la placa el jueves a las dos?", time: "2 oct, 11:02", side: "incoming" },
      { id: "m2", author: "Mateo Rulfo", body: "Jueves a las dos. Llevo la placa y la nota de tono.", time: "2 oct, 11:20", side: "outgoing", receipt: "unseen" },
    ],
  },
  {
    id: "t-envio",
    code: "BRU-9",
    subject: "Cambiar el domicilio de envío",
    description: "Cuentas se mudó de local y el pedido de gres sigue yendo al anterior.",
    requester: "Clara Neri",
    email: "clara@bruma.example",
    status: "resolved",
    priority: "low",
    type: "task",
    channel: "mail",
    assignee: "Clara Neri",
    due: "2026-09-30",
    created: "12 sep 2026",
    updated: "18 sep 2026",
    opened: "Abierta por correo · 12 sep 2026",
    sla: { text: "Cumplido", overdue: false },
    tags: ["cuentas"],
    messages: [
      { id: "m1", author: "Clara Neri", body: "El gres tiene que llegar al local nuevo, no al de la esquina.", time: "12 sep", side: "incoming" },
    ],
  },
  {
    id: "t-bucle",
    code: "BRU-31",
    subject: "El acceso de proveedores entra en bucle",
    description: "Después de identificarse, la puerta del almacén vuelve a pedir la clave.",
    requester: "Nuria Paz",
    email: "nuria@bruma.example",
    status: "open",
    priority: "urgent",
    type: "incident",
    channel: "phone",
    assignee: "Mateo Rulfo",
    due: "2026-10-04",
    created: "4 oct 2026",
    updated: "5 oct 2026",
    opened: "Abierta por teléfono · 4 oct 2026",
    sla: { text: "Vencido", overdue: true },
    tags: ["acceso"],
    messages: [
      { id: "m1", author: "Nuria Paz", body: "Los proveedores dan la clave y el acceso los regresa al inicio.", time: "4 oct, 09:12", side: "incoming" },
    ],
  },
  {
    id: "t-atajo",
    code: "BRU-4",
    subject: "Atajo para saltar entre bandejas",
    description: "Quien escribe en el escritorio quiere ir de la bandeja al hilo sin el ratón.",
    requester: "Mateo Rulfo",
    email: "mateo@bruma.example",
    status: "closed",
    priority: "low",
    type: "task",
    channel: "counter",
    assignee: "Mateo Rulfo",
    due: "2026-08-01",
    created: "1 ago 2026",
    updated: "8 ago 2026",
    opened: "Abierta en el mostrador · 1 ago 2026",
    tags: ["escritorio"],
    messages: [
      { id: "m1", author: "Mateo Rulfo", body: "Con j y k debería bastar para bajar por la lista.", time: "1 ago", side: "outgoing", receipt: "seen" },
    ],
  },
]

const nieblaComments: ThreadComment[] = [
  {
    id: "note-1",
    author: { id: "clara", name: "Clara Neri" },
    body: "El precalentado del horno 2 se corta antes de cerrar el esmalte. ¿Puedes mirar el registro de ayer?",
    createdAt: "hace 3 meses",
  },
  {
    id: "note-2",
    author: { id: "mateo", name: "Mateo Rulfo" },
    body: "El termopar marca bien hasta 900 y luego se aplana. Lo cambio el lunes.",
    createdAt: "hace 3 meses",
  },
]

export const brumaNotificationCopy: Partial<NotificationInboxCopy> = {
  title: "Avisos",
  search: "Buscar avisos",
  all: "Todos",
  unread: "Sin leer",
  teams: "Equipos",
  starred: "Destacados",
  markRead: "Marcar leídos",
  more: "Más",
  empty: "Nada en esta pestaña",
  emptyHint: "Estás al día.",
  emptySelection: "Elige un aviso",
  subscribe: "Suscribirse",
  unsubscribe: "Dejar de seguir",
  snooze: "Posponer",
  unsnooze: "Reanudar",
  archive: "Archivar",
  unstar: "Quitar destacado",
  star: "Destacar",
  remove: "Borrar",
  back: "Volver",
  activity: "Actividad",
  properties: "Propiedades",
  status: "Estado",
  priority: "Prioridad",
  labels: "Etiquetas",
  snoozed: "Pospuesto",
}

export const brumaNotifications: DeskNotification[] = [
  {
    id: "n-clara",
    actor: "Clara Neri",
    summary: "comentó en tu nota",
    title: "El horno 2 no sostiene la temperatura",
    body: "La carga de Niebla se queda cruda y frena la entrega de la barra.",
    time: "hace 3 meses",
    issueKey: "BRU-18",
    project: "Colección Niebla",
    status: "progress",
    priority: "high",
    unread: true,
    starred: false,
    team: false,
    snoozed: false,
    archived: false,
    subscribed: true,
    banner: "Clara Neri comentó en esta pieza · hace 3 meses",
    labels: ["horno", "infra"],
    comments: nieblaComments,
  },
  {
    id: "n-bruno",
    actor: "Bruno Hale",
    summary: "te asignó una pieza",
    title: "Cambiar el termopar del horno 2",
    body: "Sin el recambio, la siguiente quema vuelve a quedarse corta.",
    time: "hace 3 meses",
    issueKey: "BRU-6",
    project: "Horno",
    status: "open",
    priority: "urgent",
    unread: true,
    starred: true,
    team: true,
    snoozed: false,
    archived: false,
    subscribed: true,
    banner: "Bruno Hale te asignó esta pieza · hace 3 meses",
    labels: ["horno"],
    comments: [
      {
        id: "b1",
        author: { id: "bruno", name: "Bruno Hale" },
        body: "El repuesto llega el martes. No enciendas el horno antes.",
        createdAt: "hace 3 meses",
      },
    ],
  },
  {
    id: "n-nuria",
    actor: "Nuria Paz",
    summary: "respondió en la obra",
    title: "Juntas del muro de la cocina",
    body: "La nivelación ya está. Falta el plano de juntas de 2 mm.",
    time: "hace 2 meses",
    issueKey: "BRU-11",
    project: "Obra Faro",
    status: "progress",
    priority: "medium",
    unread: false,
    starred: true,
    team: true,
    snoozed: false,
    archived: false,
    subscribed: false,
    banner: "Nuria Paz respondió en la obra · hace 2 meses",
    labels: ["obra"],
    comments: [
      {
        id: "u1",
        author: { id: "nuria", name: "Nuria Paz" },
        body: "Si la junta baja a 1 mm, la loseta no entra.",
        createdAt: "hace 2 meses",
      },
    ],
  },
  {
    id: "n-ines",
    actor: "Inés Soler",
    summary: "pidió una muestra",
    title: "Placa de Niebla con luz del norte",
    body: "Quiere ver la placa en la barra antes de encargar el muro.",
    time: "hace 1 mes",
    issueKey: "BRU-22",
    project: "Colección Niebla",
    status: "open",
    priority: "medium",
    unread: false,
    starred: false,
    team: false,
    snoozed: true,
    archived: false,
    subscribed: true,
    banner: "Inés Soler pidió una muestra · hace 1 mes",
    labels: ["faro"],
    comments: [],
  },
  {
    id: "n-archivo",
    actor: "Clara Neri",
    summary: "cerró el domicilio",
    title: "Domicilio nuevo de cuentas",
    body: "El gres ya llega al local nuevo.",
    time: "hace 1 mes",
    issueKey: "BRU-9",
    project: "Cuentas",
    status: "resolved",
    priority: "low",
    unread: false,
    starred: false,
    team: true,
    snoozed: false,
    archived: false,
    subscribed: false,
    banner: "Clara Neri cerró esta pieza · hace 1 mes",
    labels: ["cuentas"],
    comments: [],
  },
]

export const LONG_TOKEN = "NieblaNieblaNieblaNieblaNieblaNieblaNieblaNieblaNieblaNiebla"
