/**
 * Demo presets for the same review desk. Domain words live here, not in the registry.
 *
 * Build your own:
 * 1. Call defineReviewDesk with nav, tabs, statuses, stages, records, issues, and submission.
 * 2. Pass a partial `copy` object. `{token}` placeholders (name, count, score, fee) stay in English keys.
 * 3. Point scoreIssueId at the finding whose fix swaps score.open for score.resolved.
 * 4. Render <ReviewDesk config={yourPreset} />. The block does not know the domain.
 */

import {
  defineReviewDesk,
  type ReviewDeskConfig,
  type ReviewDocument,
  type ReviewIssue,
  type ReviewPerson,
  type ReviewRecord,
  type StatusTone,
} from "@/registry/retana/lib/review-desk"

function person(id: string, name: string, role: string, owner = false): ReviewPerson {
  return { id, name, role, owner }
}

function record(
  input: Pick<ReviewRecord, "id" | "code" | "title" | "subtitle" | "place" | "statusId" | "stageId" | "progress" | "ownerId"> &
    Partial<ReviewRecord>,
): ReviewRecord {
  return {
    specs: [],
    fields: [],
    members: [],
    updated: "06 Oct",
    ...input,
  }
}

function finding(
  input: Pick<ReviewIssue, "id" | "recordId" | "title" | "detail" | "severity" | "badge" | "explanation" | "before" | "after"> &
    Partial<ReviewIssue> & { ref: string; field: string; resolvedTitle: string },
): ReviewIssue {
  const { ref, field, resolvedTitle, ...rest } = input
  return {
    blocks: input.severity === "critical",
    highlightRow: 1,
    region: input.title,
    caption: input.detail,
    location: field,
    references: [{ id: `${input.id}-ref`, title: ref, detail: input.detail }],
    recommendation: { title: resolvedTitle, body: input.explanation, fields: [{ label: field }] },
    resolved: {
      title: resolvedTitle,
      detail: input.detail,
      badge: "Waiting",
      waiting: "Waiting",
      callout: resolvedTitle,
      calloutBody: input.explanation,
    },
    changes: [{ id: `${input.id}-change`, kind: "edit", title: field, detail: input.explanation }],
    ...rest,
  }
}

const tone = (id: string, label: string, toneName: StatusTone) => ({ id, label, tone: toneName })

function shell(config: ReviewDeskConfig) {
  return defineReviewDesk(config)
}

const lumenOwner = person("ines", "Inés Soler", "Responsable", true)
const lumenTeo = person("teo", "Teo Marín", "Diseño")
const lumenLuz = person("luz", "Luz Peña", "Campo")

export const lumen = shell({
  id: "lumen",
  brand: "Taller Lumen",
  userName: "Inés Soler",
  userRole: "Revisión",
  workspace: {
    name: "Bahía Marea",
    detail: "Taller norte",
    options: [
      { id: "bahia", name: "Bahía Marea", detail: "Taller norte" },
      { id: "nispero", name: "Pueblo Níspero", detail: "Taller sur" },
    ],
  },
  assistantName: "Lumen",
  assistantDetail: "Revisa planos y sellos",
  tabs: [
    { id: "summary", label: "Resumen", panel: "summary" },
    { id: "documents", label: "Documentos", count: 4, panel: "documents" },
    { id: "package", label: "Expediente", panel: "submission" },
    { id: "notes", label: "Notas", panel: "notes" },
  ],
  nav: [
    { id: "home", items: [{ id: "overview", label: "Inicio", icon: "grid", view: "overview" }] },
    {
      id: "work",
      label: "Trabajo",
      items: [
        { id: "sites", label: "Sitios", icon: "folder", count: 3, view: "collection" },
        { id: "open", label: "Expediente abierto", icon: "file", view: "record" },
      ],
    },
  ],
  copy: {
    collectionTitle: "Sitios",
    documents: "Documentos",
    issues: "Hallazgos",
    packageTitle: "Expediente",
    submit: "Presentar expediente",
    submitTitle: "¿Presentar este expediente?",
    submitBody: "El destino recibe el paquete. Desde aquí no se deshace.",
    confirmPay: "Presentar",
    applyTitle: "¿Dejar que Lumen corrija el sello?",
    greeting: "Hola, {name}",
    attentionPill: "{count} por atender",
    search: "Buscar sitios",
    create: "Nuevo sitio",
    pipeline: "Etapas",
    openPipeline: "Abrir",
    progress: "Avance",
    requirements: "Requisitos",
    activity: "Actividad",
    details: "Ficha",
    team: "Equipo",
    codeColumn: "Código",
    dueColumn: "Fecha",
    riskColumn: "Riesgo",
    activityAll: "Todo",
    blocks: "Frena el envío",
    passed: "En orden",
    beforeSubmit: "Antes de presentar",
    deadline: "Recibe hasta {until}",
    fixOne: "Corregir con Lumen",
    fixAll: "Corregir abiertos",
    undo: "Deshacer",
    nextIssue: "Siguiente hallazgo",
    ranked: "Para revisar",
    openQueue: "Cola",
    navigation: "Secciones",
    noteReply: "Respuesta",
    noteInternal: "Nota",
    noteReplyPlaceholder: "Escribe una respuesta",
    notePlaceholder: "Escribe una nota interna",
    noteSend: "Guardar",
    notesList: "Notas guardadas",
  },
  statuses: [
    tone("draft", "Borrador", "neutral"),
    tone("review", "En revisión", "warning"),
    tone("ready", "Listo", "accent"),
    tone("filed", "Presentado", "positive"),
    tone("missing", "Falta", "critical"),
  ],
  stages: [
    { id: "site", label: "Sitio", meta: "Levantamiento" },
    { id: "design", label: "Diseño", meta: "Planos" },
    { id: "check", label: "Revisión", meta: "Hallazgos" },
    { id: "file", label: "Expediente", meta: "Envío" },
  ],
  periods: [
    { id: "week", label: "Semana" },
    { id: "month", label: "Mes" },
    { id: "quarter", label: "Trimestre" },
  ],
  defaultPeriod: "month",
  kpis: [
    { id: "open", label: "Abiertos", value: "12", detail: "en el taller", featured: true },
    { id: "ready", label: "Listos", value: "4", detail: "para presentar" },
    { id: "wait", label: "Espera", value: "3", detail: "de un sello" },
    { id: "score", label: "Puntaje", value: "81", detail: "promedio" },
  ],
  pipeline: [
    { id: "site", label: "Sitio", value: 4 },
    { id: "design", label: "Diseño", value: 5, emphasis: true },
    { id: "check", label: "Revisión", value: 2 },
    { id: "file", label: "Expediente", value: 1 },
  ],
  pipelineMeta: "Tres sitios piden un sello",
  records: [
    record({
      id: "marea",
      code: "LM-441",
      title: "Azotea Marea",
      subtitle: "Ocho módulos",
      place: "Bahía Marea",
      statusId: "review",
      stageId: "check",
      progress: 74,
      ownerId: "ines",
      featured: true,
      attention: true,
      risk: "high",
      blocker: "Sello de estructura",
      due: "18 Oct",
      updated: "Hoy",
      specs: [
        { label: "Módulos", value: "8" },
        { label: "Techo", value: "Losa" },
        { label: "Fase", value: "Revisión" },
      ],
      chips: [{ label: "Losa" }, { label: "8 módulos" }],
      facets: { town: "marea", owner: "ines" },
      fields: [
        { label: "Sitio", value: "Bahía Marea" },
        { label: "Código", value: "LM-441" },
        { label: "Destino", value: "Mesa del litoral" },
      ],
      members: [lumenOwner, lumenTeo, lumenLuz],
      event: { title: "Visita de sello", when: "Jue 09:30", action: "Ver agenda" },
    }),
    record({
      id: "nispero",
      code: "LM-228",
      title: "Taller Níspero",
      subtitle: "Cubierta metálica",
      place: "Pueblo Níspero",
      statusId: "ready",
      stageId: "file",
      progress: 91,
      ownerId: "teo",
      attention: true,
      risk: "medium",
      blocker: "Firma del vecino",
      due: "22 Oct",
      specs: [
        { label: "Módulos", value: "14" },
        { label: "Techo", value: "Metal" },
      ],
      facets: { town: "nispero", owner: "teo" },
      members: [lumenTeo],
      fields: [{ label: "Sitio", value: "Pueblo Níspero" }],
    }),
    record({
      id: "cala",
      code: "LM-117",
      title: "Cala Quietud",
      subtitle: "Suelo",
      place: "Cala Quietud",
      statusId: "draft",
      stageId: "site",
      progress: 28,
      ownerId: "luz",
      risk: "low",
      due: "02 Nov",
      specs: [
        { label: "Módulos", value: "4" },
        { label: "Techo", value: "Suelo" },
      ],
      facets: { town: "cala", owner: "luz" },
      members: [lumenLuz],
      fields: [{ label: "Sitio", value: "Cala Quietud" }],
    }),
  ],
  filters: [
    { id: "all", label: "Todos", match: "all" },
    { id: "attention", label: "Atención", match: "attention" },
    { id: "review", label: "En revisión", match: "status", value: "review" },
    { id: "ready", label: "Avanzados", match: "progress", minProgress: 80 },
  ],
  facets: [
    {
      id: "town",
      label: "Lugar",
      icon: "pin",
      options: [
        { id: "any", label: "Cualquier lugar" },
        { id: "marea", label: "Bahía Marea" },
        { id: "nispero", label: "Pueblo Níspero" },
      ],
    },
    {
      id: "owner",
      label: "Responsable",
      icon: "users",
      options: [
        { id: "any", label: "Cualquiera" },
        { id: "ines", label: "Inés Soler" },
        { id: "teo", label: "Teo Marín" },
      ],
    },
  ],
  groups: [
    { id: "plans", label: "Planos", icon: "file" },
    { id: "site", label: "Sitio", icon: "home" },
  ],
  documents: [
    doc("seal", "marea", "plans", "Plano de sello", "Rev B", "review", 0.62, "Hoy", "2", "Borrador"),
    doc("one-line", "marea", "plans", "Unifilar", "Rev A", "ready", 0.94, "Ayer", "1", "Listo"),
    doc("photo", "marea", "site", "Foto de losa", "Campo", "ready", 0.88, "Lun", "3", "Listo"),
    doc("letter", "marea", "site", "Carta de vecindad", "Falta firma", "missing", null, null, "1", "Falta"),
  ],
  docFilters: [
    { id: "all", label: "Todos" },
    { id: "plans", label: "Planos", groupId: "plans" },
    { id: "site", label: "Sitio", groupId: "site" },
  ],
  activities: [
    { id: "a1", recordId: "marea", title: "Lumen marcó el sello", detail: "El recuadro no coincide con la losa.", at: "09:12", source: "assistant", marker: "current", chips: [{ label: "Sello", tone: "warning" }] },
    { id: "a2", recordId: "marea", title: "Teo subió el unifilar", detail: "Rev A, una página.", at: "Ayer", source: "people", marker: "done" },
    { id: "a3", recordId: "marea", title: "Se abrió el expediente", detail: "LM-441", at: "Lun", source: "system", marker: "done" },
  ],
  tiles: [
    { id: "t1", recordId: "marea", value: "8", label: "Módulos", featured: true },
    { id: "t2", recordId: "marea", value: "Losa", label: "Techo" },
    { id: "t3", recordId: "marea", value: "2", label: "Planos" },
    { id: "t4", recordId: "marea", value: "1", label: "Falta" },
  ],
  issues: [
    finding({
      id: "seal",
      recordId: "marea",
      documentId: "seal",
      title: "Sello de estructura",
      detail: "El recuadro no cubre la losa.",
      severity: "critical",
      badge: "Crítico",
      explanation: "El sello queda corto respecto del plano de sitio.",
      before: ["Sello 4.2 m", "Losa 6.1 m"],
      after: ["Sello 6.1 m", "Losa 6.1 m"],
      ref: "Nota de estructura del taller",
      field: "Sello",
      resolvedTitle: "Sello alineado",
      blocks: true,
    }),
    finding({
      id: "neighbor",
      recordId: "marea",
      documentId: "letter",
      title: "Firma del vecino",
      detail: "La carta no tiene firma.",
      severity: "minor",
      badge: "Menor",
      blocks: false,
      explanation: "Falta la firma en la carta de vecindad.",
      before: ["Firma: vacía"],
      after: ["Firma: pendiente de persona"],
      ref: "Carta de vecindad",
      field: "Firma",
      resolvedTitle: "Firma pedida",
    }),
    finding({
      id: "unifilar",
      recordId: "marea",
      documentId: "one-line",
      title: "Unifilar",
      detail: "La revisión A está completa.",
      severity: "pass",
      badge: "En orden",
      blocks: false,
      explanation: "No hay diferencia contra el plano de sitio.",
      before: ["Rev A"],
      after: ["Rev A"],
      ref: "Unifilar",
      field: "Revisión",
      resolvedTitle: "Unifilar en orden",
    }),
  ],
  scoreIssueId: "seal",
  insights: [
    { place: "home", variant: "bullets", title: "Lumen", time: "Ahora", headline: "Tres sitios piden atención", bullets: [{ id: "b1", tone: "critical", text: "Azotea Marea no tiene el sello completo" }, { id: "b2", tone: "warning", text: "Taller Níspero espera una firma" }] },
    { recordId: "marea", place: "summary", variant: "status", title: "Lumen", headline: "El sello es el único freno", confidence: 0.86, body: "El resto de los planos ya está en orden." },
    { place: "documents", variant: "checklist", title: "Lumen", headline: "Falta una página", checks: [{ id: "c1", label: "Plano de sello" }, { id: "c2", label: "Carta de vecindad" }] },
    { place: "submission", variant: "stats", title: "Lumen", headline: "El expediente cabe en el destino", stats: [{ label: "Páginas", value: "7" }, { label: "Listos", value: "3", tone: "accent" }] },
  ],
  score: {
    open: { value: 67, passed: 1, minor: 1, critical: 1 },
    resolved: { value: 92, passed: 2, minor: 1, critical: 0 },
    caption: "Puntaje del expediente",
    sheet: "LM-441",
  },
  milestones: [
    { id: "site", label: "Sitio", meta: "Hecho" },
    { id: "design", label: "Diseño", meta: "Hecho" },
    { id: "check", label: "Revisión", meta: "Ahora" },
    { id: "file", label: "Envío", meta: "Después" },
  ],
  milestoneIndex: 2,
  packageGroups: [
    { id: "plans", label: "Planos", icon: "file" },
    { id: "site", label: "Sitio", icon: "home" },
  ],
  submission: {
    destination: { name: "Mesa del litoral", detail: "Ventanilla de obra", status: "Conectada" },
    fields: [
      { label: "Código", value: "LM-441" },
      { label: "Tasa", value: "48" },
    ],
    options: [
      { id: "copy", label: "Guardar una copia en el taller", checked: true },
      { id: "note", label: "Avisar a Teo cuando llegue el acuse", checked: true },
    ],
    confirm: [{ id: "ok", label: "Revisé el sello y la carta", required: true }],
    ready: { title: "Expediente listo", body: "Azotea Marea puede presentarse.", stats: [{ label: "Páginas", value: "7" }, { label: "Puntaje", value: "67" }] },
    filed: { title: "Expediente presentado", body: "La mesa del litoral ya tiene el paquete.", stats: [{ label: "Acuse", value: "LM-441" }, { label: "Puntaje", value: "92" }] },
    next: {
      title: "Qué sigue",
      body: "El acuse llega al taller.",
      steps: [
        { id: "n1", title: "Acuse", detail: "Queda en el historial", icon: "clipboard" },
        { id: "n2", title: "Aviso", detail: "Teo recibe la nota", icon: "mail" },
      ],
      action: "Ver seguimiento",
    },
    notice: { title: "Qué sigue", body: "El acuse llega al taller." },
    deadline: "18:00",
    fee: "48",
  },
  fixOptions: [
    { id: "stamp", label: "Alinear el sello a 6.1 m", checked: false, required: true },
    { id: "note", label: "Dejar la versión anterior en el historial", checked: true },
  ],
  versionLabel: "Rev C",
  header: { checked: "En revisión", fixed: "Cambio en espera", ready: "Listo para presentar", filed: "Presentado" },
  contextLine: "Bahía Marea · LM-441",
  attentionUpdated: "Actualizado hoy",
  progressCaption: "Revisión de sellos",
})

const brumaVera = person("vera", "Vera Bruma", "Dueña de la cuenta", true)
const brumaLeo = person("leo", "Leo Bruma", "Propuesta")

export const bruma = shell({
  id: "bruma",
  brand: "Estudio Bruma",
  userName: "Vera Bruma",
  userRole: "Cuentas",
  workspace: {
    name: "Mesa comercial",
    detail: "Latam",
    options: [
      { id: "latam", name: "Mesa comercial", detail: "Latam" },
      { id: "eu", name: "Mesa Europa", detail: "Socios" },
    ],
  },
  assistantName: "Bruma",
  assistantDetail: "Revisa datos y riesgos del trato",
  tabs: [
    { id: "summary", label: "Resumen", panel: "summary" },
    { id: "documents", label: "Documentos", count: 3, panel: "documents" },
    { id: "package", label: "Contrato", panel: "submission" },
    { id: "notes", label: "Notas", panel: "notes" },
  ],
  nav: [
    { id: "home", items: [{ id: "overview", label: "Inicio", icon: "grid", view: "overview" }] },
    {
      id: "work",
      label: "Pipeline",
      items: [
        { id: "deals", label: "Tratos", icon: "folder", count: 3, view: "collection" },
        { id: "open", label: "Trato abierto", icon: "file", view: "record" },
      ],
    },
  ],
  copy: {
    collectionTitle: "Tratos",
    issues: "Riesgos",
    packageTitle: "Contrato",
    submit: "Cerrar trato",
    submitTitle: "¿Cerrar este trato?",
    submitBody: "El contrato queda firmado en la mesa. Desde aquí no se deshace.",
    confirmPay: "Cerrar",
    applyTitle: "¿Completar el presupuesto?",
    greeting: "Hola, {name}",
    search: "Buscar tratos",
    create: "Nuevo trato",
    pipeline: "Embudo",
    codeColumn: "Código",
    dueColumn: "Cierre",
    riskColumn: "Riesgo",
    activityAll: "Todo",
    blocks: "Frena el cierre",
    fixOne: "Completar con Bruma",
    undo: "Deshacer",
    ranked: "Por cerrar",
    documents: "Documentos",
    noteReply: "Respuesta",
    noteInternal: "Nota",
    noteReplyPlaceholder: "Escribe una respuesta",
    notePlaceholder: "Escribe una nota interna",
    noteSend: "Guardar",
    notesList: "Notas guardadas",
  },
  statuses: [
    tone("lead", "Lead", "neutral"),
    tone("proposal", "Propuesta", "info"),
    tone("talks", "Negociación", "warning"),
    tone("won", "Ganado", "positive"),
    tone("gap", "Dato faltante", "critical"),
  ],
  stages: [
    { id: "lead", label: "Lead" },
    { id: "proposal", label: "Propuesta" },
    { id: "talks", label: "Negociación" },
    { id: "close", label: "Cierre" },
  ],
  periods: [
    { id: "month", label: "Mes" },
    { id: "quarter", label: "Trimestre" },
  ],
  defaultPeriod: "quarter",
  kpis: [
    { id: "open", label: "Abiertos", value: "9", detail: "en el embudo", featured: true },
    { id: "value", label: "Valor", value: "420k", detail: "ponderado" },
    { id: "risk", label: "Con riesgo", value: "2", detail: "dato o alcance" },
    { id: "close", label: "Este mes", value: "1", detail: "listo para firma" },
  ],
  pipeline: [
    { id: "lead", label: "Lead", value: 4 },
    { id: "proposal", label: "Propuesta", value: 3, emphasis: true },
    { id: "talks", label: "Negociación", value: 1 },
    { id: "close", label: "Cierre", value: 1 },
  ],
  pipelineMeta: "Hotel Níspero espera el presupuesto",
  records: [
    record({
      id: "hotel",
      code: "EB-310",
      title: "Hotel Níspero",
      subtitle: "Identidad y sitio",
      place: "Pueblo Níspero",
      statusId: "talks",
      stageId: "talks",
      progress: 68,
      ownerId: "vera",
      featured: true,
      attention: true,
      risk: "high",
      blocker: "Presupuesto incompleto",
      due: "20 Oct",
      specs: [
        { label: "Valor", value: "180k" },
        { label: "Etapa", value: "Negociación" },
      ],
      chips: [{ label: "180k" }, { label: "Negociación" }],
      facets: { owner: "vera", stage: "talks" },
      fields: [
        { label: "Cuenta", value: "Hotel Níspero" },
        { label: "Valor", value: "180k" },
        { label: "Contacto", value: "Sol Ibarra" },
      ],
      members: [brumaVera, brumaLeo, person("sol", "Sol Ibarra", "Cliente")],
      event: { title: "Llamada de cierre", when: "Vie 16:00", action: "Abrir agenda" },
    }),
    record({
      id: "cala",
      code: "EB-204",
      title: "Cala Quietud",
      subtitle: "Campaña de temporada",
      place: "Cala Quietud",
      statusId: "proposal",
      stageId: "proposal",
      progress: 44,
      ownerId: "leo",
      attention: true,
      risk: "medium",
      blocker: "Alcance sin firma",
      due: "28 Oct",
      specs: [
        { label: "Valor", value: "64k" },
        { label: "Etapa", value: "Propuesta" },
      ],
      facets: { owner: "leo", stage: "proposal" },
      members: [brumaLeo],
      fields: [{ label: "Cuenta", value: "Cala Quietud" }],
    }),
    record({
      id: "faro",
      code: "EB-118",
      title: "Faro Bruma",
      subtitle: "Retainer",
      place: "Bahía Marea",
      statusId: "lead",
      stageId: "lead",
      progress: 15,
      ownerId: "vera",
      risk: "low",
      due: "12 Nov",
      specs: [
        { label: "Valor", value: "24k" },
        { label: "Etapa", value: "Lead" },
      ],
      facets: { owner: "vera", stage: "lead" },
      members: [brumaVera],
      fields: [{ label: "Cuenta", value: "Faro Bruma" }],
    }),
  ],
  filters: [
    { id: "all", label: "Todos", match: "all" },
    { id: "attention", label: "Atención", match: "attention" },
    { id: "talks", label: "Negociación", match: "stage", value: "talks" },
  ],
  facets: [
    {
      id: "owner",
      label: "Dueño",
      icon: "users",
      options: [
        { id: "any", label: "Cualquiera" },
        { id: "vera", label: "Vera Bruma" },
        { id: "leo", label: "Leo Bruma" },
      ],
    },
    {
      id: "stage",
      label: "Etapa",
      icon: "chart",
      options: [
        { id: "any", label: "Cualquier etapa" },
        { id: "talks", label: "Negociación" },
        { id: "proposal", label: "Propuesta" },
      ],
    },
  ],
  groups: [
    { id: "deal", label: "Trato", icon: "file" },
    { id: "legal", label: "Contrato", icon: "clipboard" },
  ],
  documents: [
    doc("budget", "hotel", "deal", "Presupuesto", "Faltan partidas", "gap", 0.54, "Hoy", "4", "Borrador"),
    doc("scope", "hotel", "deal", "Alcance", "Sin firma", "talks", 0.8, "Ayer", "6", "Negociación"),
    doc("msa", "hotel", "legal", "Contrato marco", "Listo", "won", 0.96, "Lun", "9", "Listo"),
  ],
  docFilters: [
    { id: "all", label: "Todos" },
    { id: "deal", label: "Trato", groupId: "deal" },
    { id: "legal", label: "Contrato", groupId: "legal" },
  ],
  activities: [
    { id: "b1", recordId: "hotel", title: "Bruma vio el presupuesto", detail: "Faltan las partidas de producción.", at: "11:04", source: "assistant", marker: "current" },
    { id: "b2", recordId: "hotel", title: "Sol pidió el alcance", detail: "Aún no firma.", at: "Ayer", source: "people", marker: "done" },
  ],
  tiles: [
    { id: "v", recordId: "hotel", value: "180k", label: "Valor", featured: true },
    { id: "s", recordId: "hotel", value: "3", label: "Documentos" },
    { id: "r", recordId: "hotel", value: "1", label: "Riesgo" },
    { id: "d", recordId: "hotel", value: "Vie", label: "Llamada" },
  ],
  issues: [
    finding({
      id: "budget",
      recordId: "hotel",
      documentId: "budget",
      title: "Presupuesto incompleto",
      detail: "Faltan las partidas de producción.",
      severity: "critical",
      badge: "Crítico",
      explanation: "Sin esas partidas el contrato no cierra.",
      before: ["Producción: —"],
      after: ["Producción: 42k"],
      ref: "Plantilla de presupuesto",
      field: "Producción",
      resolvedTitle: "Presupuesto completo",
    }),
    finding({
      id: "scope",
      recordId: "hotel",
      documentId: "scope",
      title: "Alcance sin firma",
      detail: "Sol no firmó el alcance.",
      severity: "minor",
      badge: "Menor",
      blocks: false,
      explanation: "El alcance está escrito y espera firma.",
      before: ["Firma: no"],
      after: ["Firma: pedida"],
      ref: "Alcance EB-310",
      field: "Firma",
      resolvedTitle: "Firma pedida",
    }),
  ],
  scoreIssueId: "budget",
  insights: [
    { place: "home", variant: "bullets", title: "Bruma", headline: "Un trato puede cerrar esta semana", bullets: [{ id: "h", tone: "critical", text: "Hotel Níspero no tiene presupuesto completo" }] },
    { recordId: "hotel", place: "summary", variant: "status", title: "Bruma", headline: "El cierre depende del presupuesto", confidence: 0.74 },
    { place: "documents", variant: "stats", title: "Bruma", headline: "Dos documentos todavía se mueven", stats: [{ label: "Listos", value: "1", tone: "accent" }, { label: "Abiertos", value: "2", tone: "warning" }] },
    { place: "submission", variant: "checklist", title: "Bruma", headline: "El contrato puede salir", checks: [{ id: "k", label: "Presupuesto" }, { id: "s", label: "Alcance" }] },
  ],
  score: {
    open: { value: 50, passed: 0, minor: 1, critical: 1 },
    resolved: { value: 84, passed: 1, minor: 1, critical: 0 },
    caption: "Salud del trato",
    sheet: "EB-310",
  },
  milestones: [
    { id: "lead", label: "Lead", meta: "Hecho" },
    { id: "proposal", label: "Propuesta", meta: "Hecho" },
    { id: "talks", label: "Negociación", meta: "Ahora" },
    { id: "close", label: "Cierre", meta: "Después" },
  ],
  milestoneIndex: 2,
  packageGroups: [
    { id: "deal", label: "Trato", icon: "file" },
    { id: "legal", label: "Contrato", icon: "clipboard" },
  ],
  submission: {
    destination: { name: "Mesa de firma", detail: "Contratos", status: "Abierta" },
    fields: [
      { label: "Trato", value: "EB-310" },
      { label: "Valor", value: "180k" },
    ],
    options: [{ id: "copy", label: "Enviar copia a Sol", checked: true }],
    confirm: [{ id: "ok", label: "El presupuesto ya está completo", required: true }],
    ready: { title: "Contrato listo", body: "Hotel Níspero puede cerrarse.", stats: [{ label: "Valor", value: "180k" }] },
    filed: { title: "Trato cerrado", body: "La mesa de firma tiene el contrato.", stats: [{ label: "Código", value: "EB-310" }] },
    next: { title: "Qué sigue", body: "Sol recibe la copia.", steps: [{ id: "n", title: "Copia", detail: "Sale hoy", icon: "send" }], action: "Ver trato" },
    notice: { title: "Qué sigue", body: "Sol recibe la copia." },
    deadline: "18:00",
    fee: "0",
  },
  fixOptions: [{ id: "budget", label: "Agregar la partida de producción", checked: false, required: true }],
  versionLabel: "v3",
  header: { checked: "En negociación", fixed: "Cambio en espera", ready: "Listo para cerrar", filed: "Cerrado" },
  contextLine: "Hotel Níspero · EB-310",
  attentionUpdated: "Actualizado hoy",
  progressCaption: "De lead a cierre",
})

const costaNia = person("nia", "Nia Costa", "Reviewer", true)
const costaMateo = person("mateo", "Mateo Rivas", "Analyst")

export const costa = shell({
  id: "costa",
  brand: "Caja Costa",
  userName: "Nia Costa",
  userRole: "Reviewer",
  workspace: {
    name: "Credit desk",
    detail: "North branch",
    options: [
      { id: "north", name: "Credit desk", detail: "North branch" },
      { id: "south", name: "Credit desk", detail: "South branch" },
    ],
  },
  assistantName: "Costa",
  assistantDetail: "Checks the file before a decision",
  tabs: [
    { id: "summary", label: "Summary", panel: "summary" },
    { id: "documents", label: "Documents", count: 3, panel: "documents" },
    { id: "package", label: "Credit file", panel: "submission" },
    { id: "notes", label: "Notes", panel: "notes" },
  ],
  nav: [
    { id: "home", items: [{ id: "overview", label: "Overview", icon: "grid", view: "overview" }] },
    {
      id: "work",
      label: "Queue",
      items: [
        { id: "files", label: "Files", icon: "folder", count: 3, view: "collection" },
        { id: "open", label: "Open file", icon: "file", view: "record" },
      ],
    },
  ],
  copy: {
    collectionTitle: "Files",
    issues: "Issues",
    packageTitle: "Credit file",
    submit: "Approve file",
    submitTitle: "Approve this credit file?",
    submitBody: "This records the decision and cannot be undone from here.",
    confirmPay: "Approve",
    apply: "Apply change",
    applyTitle: "Apply the income note?",
    applyBody: "You approve the note before it is saved.",
    blocks: "Blocks approval",
    codeColumn: "ID",
    dueColumn: "Due",
    riskColumn: "Risk",
    activityAll: "All",
  },
  statuses: [
    tone("intake", "Intake", "neutral"),
    tone("review", "In review", "warning"),
    tone("ready", "Ready", "accent"),
    tone("approved", "Approved", "positive"),
    tone("gap", "Gap", "critical"),
  ],
  stages: [
    { id: "intake", label: "Intake" },
    { id: "review", label: "Review" },
    { id: "conditions", label: "Conditions" },
    { id: "decision", label: "Decision" },
  ],
  periods: [
    { id: "week", label: "Week" },
    { id: "month", label: "Month" },
  ],
  defaultPeriod: "week",
  kpis: [
    { id: "open", label: "Open files", value: "6", detail: "on the desk", featured: true },
    { id: "ready", label: "Ready", value: "2", detail: "for a decision" },
    { id: "gaps", label: "Gaps", value: "3", detail: "income or identity" },
    { id: "score", label: "Median", value: "71", detail: "file score" },
  ],
  pipeline: [
    { id: "intake", label: "Intake", value: 2 },
    { id: "review", label: "Review", value: 2, emphasis: true },
    { id: "conditions", label: "Conditions", value: 1 },
    { id: "decision", label: "Decision", value: 1 },
  ],
  pipelineMeta: "Harbor line is waiting on income",
  records: [
    record({
      id: "harbor",
      code: "CC-1842",
      title: "Harbor line",
      subtitle: "Working capital",
      place: "Puerto Níspero",
      statusId: "review",
      stageId: "conditions",
      progress: 72,
      ownerId: "nia",
      featured: true,
      attention: true,
      risk: "high",
      blocker: "Income gap",
      due: "16 Oct",
      specs: [
        { label: "Amount", value: "90k" },
        { label: "Stage", value: "Conditions" },
      ],
      chips: [{ label: "90k" }, { label: "Conditions" }],
      facets: { owner: "nia", branch: "north" },
      fields: [
        { label: "File", value: "CC-1842" },
        { label: "Amount", value: "90k" },
        { label: "Borrower", value: "Harbor co-op" },
      ],
      members: [costaNia, costaMateo],
      event: { title: "Committee", when: "Thu 15:00", action: "Open calendar" },
    }),
    record({
      id: "dune",
      code: "CC-1760",
      title: "Dune shop",
      subtitle: "Equipment",
      place: "Cala Quietud",
      statusId: "ready",
      stageId: "decision",
      progress: 88,
      ownerId: "mateo",
      attention: true,
      risk: "low",
      blocker: "Identity mismatch",
      due: "19 Oct",
      specs: [
        { label: "Amount", value: "22k" },
        { label: "Stage", value: "Decision" },
      ],
      facets: { owner: "mateo", branch: "south" },
      members: [costaMateo],
      fields: [{ label: "File", value: "CC-1760" }],
    }),
    record({
      id: "pier",
      code: "CC-1502",
      title: "Pier stall",
      subtitle: "Seasonal",
      place: "Bahía Marea",
      statusId: "intake",
      stageId: "intake",
      progress: 20,
      ownerId: "nia",
      risk: "medium",
      due: "30 Oct",
      specs: [
        { label: "Amount", value: "8k" },
        { label: "Stage", value: "Intake" },
      ],
      facets: { owner: "nia", branch: "north" },
      members: [costaNia],
      fields: [{ label: "File", value: "CC-1502" }],
    }),
  ],
  filters: [
    { id: "all", label: "All", match: "all" },
    { id: "attention", label: "Attention", match: "attention" },
    { id: "review", label: "In review", match: "status", value: "review" },
  ],
  facets: [
    {
      id: "owner",
      label: "Owner",
      icon: "users",
      options: [
        { id: "any", label: "Any owner" },
        { id: "nia", label: "Nia Costa" },
        { id: "mateo", label: "Mateo Rivas" },
      ],
    },
    {
      id: "branch",
      label: "Branch",
      icon: "pin",
      options: [
        { id: "any", label: "Any branch" },
        { id: "north", label: "North" },
        { id: "south", label: "South" },
      ],
    },
  ],
  groups: [
    { id: "income", label: "Income", icon: "file" },
    { id: "identity", label: "Identity", icon: "shield" },
  ],
  documents: [
    doc("income-letter", "harbor", "income", "Income letter", "Two months short", "gap", 0.58, "Today", "3", "Gap"),
    doc("id-scan", "harbor", "identity", "Identity scan", "Name matches", "ready", 0.93, "Yesterday", "2", "Ready"),
    doc("statement", "harbor", "income", "Bank statement", "Complete", "ready", 0.9, "Mon", "8", "Ready"),
  ],
  docFilters: [
    { id: "all", label: "All" },
    { id: "income", label: "Income", groupId: "income" },
    { id: "identity", label: "Identity", groupId: "identity" },
  ],
  activities: [
    { id: "c1", recordId: "harbor", title: "Costa flagged the income letter", detail: "Two months are missing.", at: "08:40", source: "assistant", marker: "current", chips: [{ label: "Income", tone: "critical" }] },
    { id: "c2", recordId: "harbor", title: "Mateo uploaded the scan", detail: "The name matches the file.", at: "Yesterday", source: "people", marker: "done" },
  ],
  tiles: [
    { id: "amt", recordId: "harbor", value: "90k", label: "Amount", featured: true },
    { id: "docs", recordId: "harbor", value: "3", label: "Documents" },
    { id: "gaps", recordId: "harbor", value: "1", label: "Gap" },
    { id: "meet", recordId: "harbor", value: "Thu", label: "Committee" },
  ],
  issues: [
    finding({
      id: "income-gap",
      recordId: "harbor",
      documentId: "income-letter",
      title: "Income gap",
      detail: "The letter is two months short.",
      severity: "critical",
      badge: "Critical",
      explanation: "The file needs two more months of income before a decision.",
      before: ["Months: 10"],
      after: ["Months: 12"],
      ref: "Income checklist",
      field: "Income months",
      resolvedTitle: "Income note added",
      resolved: {
        title: "Income note added",
        detail: "Two months were added to the letter.",
        badge: "Waiting",
        waiting: "Waiting on a reviewer",
        callout: "Income note added",
        calloutBody: "The previous letter stays in history.",
      },
    }),
    finding({
      id: "identity",
      recordId: "harbor",
      documentId: "id-scan",
      title: "Identity check",
      detail: "The scan matches the borrower.",
      severity: "pass",
      badge: "Pass",
      blocks: false,
      explanation: "No mismatch on the identity scan.",
      before: ["Name: Harbor co-op"],
      after: ["Name: Harbor co-op"],
      ref: "Identity scan",
      field: "Name",
      resolvedTitle: "Identity matches",
    }),
  ],
  scoreIssueId: "income-gap",
  insights: [
    { place: "home", variant: "bullets", title: "Costa", time: "Now", headline: "One file blocks a decision", bullets: [{ id: "g", tone: "critical", text: "Harbor line is short two income months" }, { id: "d", tone: "accent", text: "Dune shop is ready for committee" }] },
    { recordId: "harbor", place: "summary", variant: "status", title: "Costa", headline: "Income is the only blocker", confidence: 0.81, body: "Identity already matches." },
    { place: "documents", variant: "checklist", title: "Costa", headline: "Still open", checks: [{ id: "inc", label: "Income letter" }] },
    { place: "submission", variant: "stats", title: "Costa", headline: "The file can go to committee", stats: [{ label: "Pages", value: "13" }, { label: "Score", value: "64", tone: "warning" }] },
  ],
  score: {
    open: { value: 64, passed: 1, minor: 0, critical: 1 },
    resolved: { value: 88, passed: 2, minor: 0, critical: 0 },
    caption: "File score",
    sheet: "CC-1842",
  },
  milestones: [
    { id: "intake", label: "Intake", meta: "Done" },
    { id: "review", label: "Review", meta: "Done" },
    { id: "conditions", label: "Conditions", meta: "Now" },
    { id: "decision", label: "Decision", meta: "Next" },
  ],
  milestoneIndex: 2,
  packageGroups: [
    { id: "income", label: "Income", icon: "file" },
    { id: "identity", label: "Identity", icon: "shield" },
  ],
  submission: {
    destination: { name: "Credit committee", detail: "Thursday sitting", status: "Open" },
    fields: [
      { label: "File", value: "CC-1842" },
      { label: "Amount", value: "90k" },
    ],
    options: [
      { id: "copy", label: "Keep a copy on the desk", checked: true },
      { id: "note", label: "Tell Mateo when the decision posts", checked: false },
    ],
    confirm: [{ id: "ok", label: "I confirm this decision", required: true }],
    ready: { title: "File ready", body: "Harbor line can go to committee.", stats: [{ label: "Score", value: "64" }, { label: "Pages", value: "13" }] },
    filed: { title: "File approved", body: "The committee has the credit file.", stats: [{ label: "File", value: "CC-1842" }, { label: "Score", value: "88" }] },
    next: {
      title: "What happens next",
      body: "The decision posts to the desk.",
      steps: [
        { id: "post", title: "Decision", detail: "Posts after committee", icon: "clipboard" },
        { id: "note", title: "Note", detail: "Mateo gets a copy", icon: "mail" },
      ],
      action: "Open tracker",
    },
    notice: { title: "What happens next", body: "The decision posts to the desk." },
    deadline: "15:00",
    fee: "0",
  },
  fixOptions: [
    { id: "note", label: "I reviewed the income note", checked: false, required: true },
    { id: "history", label: "Keep the previous letter", checked: true },
  ],
  versionLabel: "Note 2",
  header: { checked: "In review", fixed: "Change waiting", ready: "Ready to approve", filed: "Approved" },
  contextLine: "Puerto Níspero · CC-1842",
  attentionUpdated: "Updated today",
  progressCaption: "Intake to decision",
})

export const reviewPresets = [
  { id: "lumen", label: "Permisos solares", detail: "Taller Lumen", config: lumen },
  { id: "bruma", label: "Trato de ventas", detail: "Estudio Bruma", config: bruma },
  { id: "costa", label: "Expediente de crédito", detail: "Caja Costa", config: costa },
] as const

function doc(
  id: string,
  recordId: string,
  groupId: string,
  name: string,
  meta: string,
  statusId: string,
  score: number | null,
  date: string | null,
  pages: string,
  state: string,
): ReviewDocument {
  return { id, recordId, groupId, name, meta, statusId, score, date, pages, state }
}
