import { spawnSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

import { rewriteRegistryImports, scanPayloadDocument } from "./installed-imports.ts"
import { validateRegistryTree, type RegistryInput } from "./validate-registry.ts"

const root = path.resolve(import.meta.dirname, "..")

function fail(errors: string[]) {
  console.error("\nRegistry validation failed:\n")
  for (const error of errors) console.error(`- ${error}`)
  process.exit(1)
}

const errors = validateRegistryTree(root)
if (errors.length) fail(errors)

const build = spawnSync("pnpm", ["exec", "shadcn", "build"], {
  cwd: root,
  stdio: "inherit",
})
if (build.status !== 0) process.exit(build.status ?? 1)

const builtDir = path.join(root, "public", "r")
const builtErrors: string[] = []
let rewritten = 0
for (const name of fs.readdirSync(builtDir)) {
  if (!name.endsWith(".json")) continue
  const filePath = path.join(builtDir, name)
  const original = fs.readFileSync(filePath, "utf8")
  const text = rewriteRegistryImports(original)
  if (text !== original) {
    fs.writeFileSync(filePath, text)
    rewritten += 1
  }
  const json = JSON.parse(text) as unknown
  if (json && typeof json === "object" && "cssVars" in json) {
    builtErrors.push(`public/r/${name} contains cssVars.`)
  }
  const items = (json as { items?: unknown[] }).items
  if (Array.isArray(items)) {
    for (const item of items) {
      if (item && typeof item === "object" && "cssVars" in item) {
        builtErrors.push(`public/r/${name} lists an item with cssVars.`)
      }
    }
  }
  if (text.includes("registry/retana")) {
    builtErrors.push(`public/r/${name} still contains registry/retana.`)
  }
  for (const error of scanPayloadDocument(json)) {
    builtErrors.push(`public/r/${name}: ${error}`)
  }
}
if (rewritten) console.log(`Rewrote install imports in ${rewritten} registry payloads.`)
if (builtErrors.length) fail(builtErrors)

const registry = JSON.parse(
  fs.readFileSync(path.join(root, "registry.json"), "utf8"),
) as RegistryInput

const imports: string[] = []
const entries: string[] = []
for (const [index, item] of (registry.items ?? []).entries()) {
  const preview = item.meta?.preview
  if (!preview) continue
  const specifier = `@/${preview.replace(/\.tsx$/, "")}`
  imports.push(`import Preview${index} from "${specifier}"`)
  entries.push(`  "${item.name}": Preview${index},`)
}

const map = `"use client"

// Generated by scripts/build-registry.ts. Do not edit.
${imports.join("\n")}

export const previewMap = {
${entries.join("\n")}
}
`

const mapPath = path.join(root, "lib", "generated", "preview-map.tsx")
fs.mkdirSync(path.dirname(mapPath), { recursive: true })
fs.writeFileSync(mapPath, map)
console.log(`Wrote ${path.relative(root, mapPath)}`)
